apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multicontainer.fullname" . }}
  labels:
    {{- include "multicontainer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "multicontainer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "multicontainer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "multicontainer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: shared
        emptyDir: {}
      containers:
        - name: app-container-poller
          image: yauritux/busybox-curl
          command: ["/bin/sh"]
          args: ["-c", "while true; do curl 127.0.0.1:81 > /usr/share/nginx/html/index.html; sleep 10; done"]
          volumeMounts:
          - name: shared
            mountPath: /usr/share/nginx/html
        - name: app-container-server
          image: nginx
          ports:
            - containerPort: 80
              name: nginx 
          volumeMounts:
          - name: shared
            mountPath: /usr/share/nginx/html
        - name: ambassador-container
          image: bharamicrosystems/nginx-forward-proxy
          ports:
            - containerPort: 81
              name: nginx81
        - name: hello-world-pod
          image: reyesoft/hello-world:latest
          ports:
          - containerPort: 8005
            name: helloworld8005
