apiVersion: v1
kind: Service
metadata:
  name: {{ include "multicontainer.fullname" . }}
  labels:
    {{- include "multicontainer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
    - port: 81
      targetPort: 81
      protocol: TCP
      name: nginx81
    - port: 8005
      targetPort: 8005
      protocol: TCP
      name: helloworld8005
  selector:
    {{- include "multicontainer.selectorLabels" . | nindent 4 }}
